### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ShalokShalom** [FractalFir/wrapped_mono#10]
Is this project completed, and ready to be used productive?

Or simply unmaintained

**Comment by FractalFir** [comment]
It is mostly done, but I have made it some time ago, before I was as experienced as I am now. 

Some of the exposed APIs are flawed(they don't enforce #[repr(C)] layout), and I'd like to redesign them in the future. 

But, besides those issues, it is done.

**Comment by ShalokShalom** [comment]
Maybe mention that in the README? 

I can send a PR

**Comment by FractalFir** [comment]
I *think* I fixed all  the API flaws / potential soundness issues - you now need to implement an unsafe marker trait to pass a value of a given type to .NET. That should, hopefully, be enough.  I also included a message about the state of the project in readme.
