### ISSUE TITLE
missing corelib_binds.rs

### ISSUE THREAD

**Issue by QEU-B-458** [FractalFir/wrapped_mono#7]
we were trying to run the test's for the library and continue to get theses errors we even tried to regen_binds but nothing changes the error  the header files are present in /usr/include/mono-2.0/mono as the build script expects

OS Debian GNU/Linux 12
Mono JIT compiler version 6.8.0.105
apt mono-complete

Compiling wrapped_mono v0.3.1 (/workspaces/New folder/wrapped_mono)
error: couldn't read src/corelib_binds.rs: No such file or directory (os error 2)
  --> src/bindgen.rs:58:35
   |
58 |             self.target.write_all(include_bytes!("corelib_binds.rs"))?;
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused imports: `Method`, `TypeDefinition`
 --> src/bindgen.rs:1:23
  |
1 | use crate::metadata::{Method, TypeDefinition};
  |                       ^^^^^^  ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `MethodTable`
 --> src/bindgen.rs:2:23
  |
2 | use crate::metadata::{MethodTable, TypeDefOrRef, TypeDefinitionTable, TypeReferenceTable};
  |                       ^^^^^^^^^^^

warning: unused import: `std::path::PathBuf`
 --> src/bindgen.rs:8:5
  |
8 | use std::path::PathBuf;
  |     ^^^^^^^^^^^^^^^^^^

warning: unused import: `MonoReflectionType`
 --> src/reflection_type.rs:1:32
  |
1 | use crate::binds::{MonoObject, MonoReflectionType, MonoType};
  |                                ^^^^^^^^^^^^^^^^^^

warning: unused imports: `InteropRecive`, `InteropSend`
 --> src/reflection_type.rs:5:27
  |
5 | use crate::{InteropClass, InteropRecive, InteropSend};
  |                           ^^^^^^^^^^^^^  ^^^^^^^^^^^

warning: `wrapped_mono` (lib) generated 5 warnings
error: could not compile `wrapped_mono` (lib) due to previous error; 5 warnings emitted

**Comment by FractalFir** [comment]
It seems you have pulled directly from GitHub? This file was indeed missing, and should now be present after 5e39dbcdd4f4cba03c290972e3ac97ae12e07801. I should however note that you would probably be better off using the stable version from `crates.io`. The GitHub version does have slightly more features, but they are mostly unfinished, as you can see from your issues. The GitHub version should not be used for anything else than development of `wrapped_mono`.

 The missing file comes from an experimental C# to Rust binding generator, something not yet included in stable versions. It is also why `regen_binds` did nothing - it is not about any binding to mono, but something only relevant to generating Rust bindings for C# libraries. Did the fix resolve your issues?

**Comment by FractalFir** [comment]
Closed because of inactivity.
